Resources:
  emailNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "emailNotificationQueue"
      VisibilityTimeout: 30

      
  slackNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "slackNotificationQueue"
      VisibilityTimeout: 30

  mySqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: mySqsQueuePolicy
        Statement:
        - Sid: Allow-sns-SendMessage
          Effect: Allow
          Principal: 
            Service: sns.amazonaws.com
          Action:
          - sqs:SendMessage
          Resource: "*"
          Condition: 
            ArnEquals:
              aws:SourceArn:
                Fn::ImportValue: MySNSTopicArn
      Queues:
        - Ref: emailNotificationQueue
        - Ref: slackNotificationQueue

Outputs:
  emailNotificationQueue:
    Value: 
      Fn::GetAtt:
          - emailNotificationQueue
          - Arn
    Export:
      Name: myemailNotificationQueue
      
  slackNotificationQueue:
    Value: 
      Fn::GetAtt:
          - slackNotificationQueue
          - Arn
    Export:
      Name: myslackNotificationQueue