Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: "coreServiceTopic"


  emailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: 
        Fn::GetAtt:
          - MySNSTopic
          - TopicArn
      Endpoint: 
        Fn::ImportValue: emailNotificationQueue
      FilterPolicy:
        eventType: 
          - USER_UPDATED
      FilterPolicyScope:
        MessageAttributes 
      Protocol: sqs

      
  slackSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: 
        Fn::GetAtt:
          - MySNSTopic
          - TopicArn
      Endpoint: 
        Fn::ImportValue: slackNotificationQueue
      FilterPolicy:
        eventType: 
          - USER_CREATED
      FilterPolicyScope:
        MessageAttributes 
      Protocol: sqs

Outputs:
  SnsTopicArn:
    Value: 
      Fn::GetAtt:
          - MySNSTopic
          - TopicArn
    Export:
      Name: MySNSTopicArn