Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: "coreServiceTopic"


  emailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: 
        Fn::GetAtt:
          - MySNSTopic
          - TopicArn
      Endpoint: 
        Fn::ImportValue: myEmailNotificationQueue
      Protocol: sqs

      
  slackSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: 
        Fn::GetAtt:
          - MySNSTopic
          - TopicArn
      Endpoint: 
        Fn::ImportValue: mySlackNotificationQueue
      Protocol: sqs

Outputs:
  SnsTopicArn:
    Value: 
      Fn::GetAtt:
          - MySNSTopic
          - TopicArn
    Export:
      Name: MySNSTopicArn